_target_: src.systems.predictor.exact_env_predictor.ExactEnvPredictor
model:
  _target_: src.systems.systems.env_systems.env_system.TimeVaryingBatchedMujocoEnv
  env_id: "my_env/TimeVarScaledHalfCheetha-v0"
  batch_size: 100
one_step_model:
  _target_: src.systems.systems.env_systems.env_system.TimeVaryingBatchedMujocoEnv
  env_id: "my_env/TimeVarScaledHalfCheetha-v0"
  batch_size: 1
batch_size: 1
pop_size: 100
device: cuda