defaults:
  - controller: random.yaml
  - interactor: interactor.yaml
  - interactor@control_interactor: interactor.yaml

_target_: src.utils.eval_scenario.control_test.VdpControlTestScenario

observation_noise: 0.001
process_noise: 0.01
chunk_size: 50
system_type:
  _target_: src.systems.systems.dynamic_system.VanDerPolType

name: ""