
defaults:
  - predictor: predictor.yaml

_target_: src.systems.control.mppi.MPPI
beta: 0.9
popsize: 1000
kappa: 0.9
noise_sigma: 1
pred_len: 30
iterations: 4
particles: 1
noise_factor: 1

state_cost:
  _target_: src.systems.enviroment.other_mppi_costs.HalfCheethaStateCost
terminal_state_cost:
  _target_: src.systems.enviroment.other_mppi_costs.HalfCheethaTerminalCost
input_cost:
  _target_: src.systems.enviroment.other_mppi_costs.HalfCheethaInputCost

input_bounds: [ [ -1, 1 ], [ -1, 1 ], [ -1, 1 ], [ -1, 1 ], [ -1, 1 ], [ -1, 1 ] ]
system_type:
  _target_: src.systems.systems.dynamic_system.HalfCheethaType

predictor:
  unroll_mode: mean_propagation