
defaults:
  - predictor: predictor.yaml

_target_: src.systems.control.mppi.MPPI
beta: 0.6
popsize: 5000
kappa: 0.9
noise_sigma: 1
pred_len: 50

state_cost:
  _target_: src.systems.enviroment.invP_env.InvPStateCost
terminal_state_cost:
  _target_: src.systems.enviroment.invP_env.InvPTerminalCost
input_cost:
  _target_: src.systems.enviroment.invP_env.InvPInputCost

input_bounds: [ [ -5, 5 ] ]
system_type:
  _target_: src.systems.systems.dynamic_system.InvertedPendulumType
