defaults:
  - predictor@controllers.0.predictor: predictor.yaml
  - predictor@controllers.1.predictor: predictor.yaml

_target_: src.systems.control.time_combined_controller.TimeCombinedController

controller_start_time: [0, 120]
trigger_controller_name: "0"
controllers:
  "0":
    _target_: src.systems.control.mppi.MPPI
    beta: 0.6
    popsize: 5000
    kappa: 0.9
    noise_sigma: 1
    pred_len: 50

    state_cost:
      _target_: src.systems.enviroment.invP_env.InvPStateCost
    terminal_state_cost:
      _target_: src.systems.enviroment.invP_env.InvPTerminalCost
    input_cost:
      _target_: src.systems.enviroment.invP_env.InvPInputCost

    input_bounds: [ [ -5, 5 ] ]
    system_type:
      _target_: src.systems.systems.dynamic_system.InvertedPendulumType

  "1":
    _target_: src.systems.control.random_controller.RandomController
    control_range: [ -5, 5 ]
    system_type:
      _target_: src.systems.systems.dynamic_system.InvertedPendulumType