
defaults:
  - predictor: predictor.yaml

_target_: src.systems.control.mppi.MPPI
beta: 0.6
popsize: 5000
kappa: 0.9
noise_sigma: 1
pred_len: 50

state_cost:
  _target_: src.systems.enviroment.env.CombinedStateCost
  weights: [ 100, 1 ]
  state_cost:
    - _target_: src.systems.enviroment.vdp_env.CircleSpeedCost
    - _target_: src.systems.enviroment.vdp_env.CircleDistanceCost
terminal_state_cost:
  _target_: src.systems.enviroment.vdp_env.CircleDistanceTerminalCost
  weight: 100
input_cost: null

input_bounds: [ [ -4, 4 ] ]
system_type:
  _target_: src.systems.systems.dynamic_system.VanDerPolType
