# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml
  - logger: null
  - trainer: default.yaml
  - callbacks: default.yaml
  - extras: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  - override hydra/launcher: submitit_slurm

task_name: "notebook"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "checkpoint-epoch"
strict_load: True
yappi-profile: False